php5:
  build: .
  restart: always
  container_name: php5
  dockerfile: ./etc/docker/dockerfile_php_5
  volumes:
    - ./sites:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
    - ./etc/php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini
  #  - ./etc/hosts:/etc/hosts
    - ./etc/logs:/var/log
  ports:
    - "80:80"
  links:
    - mysql5
  #  - smtpsrv

php7:
  build: .
  restart: always
  container_name: php7
  dockerfile: ./etc/docker/dockerfile_php_7
  volumes:
    - ./sites:/var/www/html
    - ./etc/php:/usr/local/etc/php
    - ./etc/apache2/apache2.conf:/etc/apache2/conf-enabled/apache2.conf
    - ./etc/apache2/hosts.conf:/etc/apache2/sites-enabled/hosts.conf
    - ./etc/php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini
  #  - ./etc/hosts:/etc/hosts
    - ./etc/logs:/var/log
  ports:
    - "8080:80"
  links:
    - mysql5
  #  - smtpsrv

mysql5:
  container_name: mysql
  image: mysql:5.7
  restart: always
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=000000
    - MYSQL_DATABASE=desarrollo
  volumes: 
    - ./etc/mysql:/docker-entrypoint-initdb.d
    - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    - ./etc/mysql/data:/var/lib/mysql-files

#smtpsrv:
#  image: namshi/smtp
#  restart: always
#  container_name: smtpsrv
#  ports:
#   - "25:25"
