FROM php:7.2-apache

RUN echo "INICIANDO"
RUN apt-get update && \
    apt-get install -y --install-recommends \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libpq-dev \
    pdftk \
    zip \
    zlib1g-dev \
    libicu-dev
    
RUN docker-php-ext-install gd \
    intl
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
RUN docker-php-ext-install zip
RUN docker-php-ext-install mysqli
RUN a2enmod rewrite
RUN service apache2 restart
