FROM php:5-apache

RUN echo "INICIANDO"
RUN apt-get update && \
    apt-get install -y libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev && \
    apt-get install -y ssmtp && \
    docker-php-ext-install mbstring && \
    docker-php-ext-install zip && \
    docker-php-ext-install pdo pdo_mysql && \
    docker-php-ext-install gd && \
    docker-php-ext-configure gd \
	--enable-gd-native-ttf \
	--with-freetype-dir=/usr/include/freetype2 \
	--with-png-dir=/usr/include \
	--with-jpeg-dir=/usr/include && \
    docker-php-ext-install gd

RUN apt-get update && apt-get install -y zlib1g-dev libicu-dev g++
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-install mysqli
RUN a2enmod rewrite
RUN service apache2 restart
